### ISSUE TITLE
dist folder is missing

### ISSUE THREAD

**Issue by RicoswLive** [the-obsidian/mc-discourse-sso#2]
Can't run the application dist folder is missing
Please fix it

**Comment by jacobwgillespie** [comment]
The dist folder should get built as part of `npm install` (https://github.com/the-obsidian/mc-discourse-sso/blob/master/package.json#L14).  Can you verify that `npm install` succeeds?

**Comment by RicoswLive** [comment]
My Problem now

> node-sass@3.4.2 install /home/tellurserver/mc-sso/node_modules/node-sass-middleware/node_modules/node-sass
> node scripts/install.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'npmconf'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/tellurserver/mc-sso/node_modules/node-sass-middleware/node_modules/node-sass/scripts/install.js:8:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by jacobwgillespie** [comment]
What version of node are you using?

**Comment by RicoswLive** [comment]
I have fixed it it works now

But if I login in I don't redirected to my Discourse Forum

**Comment by RicoswLive** [comment]
ReferenceError: Promise is not defined
 at Function.authenticate (/home/tellurserver/mc-discourse-sso/dist/mc.js:25:18)
 at app.listen.host (/home/tellurserver/mc-discourse-sso/dist/index.js:153:16)
 at Layer.handle [as handle_request] (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/layer.js:95:5)
 at next (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/route.js:131:13)
 at Route.dispatch (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/route.js:112:3)
 at Layer.handle [as handle_request] (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/layer.js:95:5)
 at /home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:277:22
 at Function.process_params (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:330:12)
 at next (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:271:10)
 at app.get.res.render.auth (/home/tellurserver/mc-discourse-sso/dist/index.js:91:12)
 at Layer.handle [as handle_request] (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:312:13)
 at /home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:330:12)
 at next (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:271:10)
 at jsonParser (/home/tellurserver/mc-discourse-sso/node_modules/body-parser/lib/types/json.js:93:44)
 at Layer.handle [as handle_request] (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:312:13)
 at /home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:330:12)
 at next (/home/tellurserver/mc-discourse-sso/node_modules/express/lib/router/index.js:271:10)
 at /home/tellurserver/mc-discourse-sso/node_modules/body-parser/lib/read.js:129:5
 at invokeCallback (/home/tellurserver/mc-discourse-sso/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
 at done (/home/tellurserver/mc-discourse-sso/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
 at IncomingMessage.onEnd (/home/tellurserver/mc-discourse-sso/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
 at IncomingMessage.EventEmitter.emit (events.js:92:17)
 at _stream_readable.js:920:16
 at process._tickCallback (node.js:415:13)

I become now this error

**Comment by jacobwgillespie** [comment]
Your nodejs version is likely out of date - what version are you using?

**Comment by jacobwgillespie** [comment]
Yep, that's to be expected - if you just load it up and log in it will do nothing.  However if you configure SSO on your Discourse forum and click log in there, it should redirect back afterwards.

**Comment by snowe2010** [comment]
Hm. how were you able to get it running? I still can't get it running. `npm install` is giving me this error.

```
[vagrant@precise32:/vagrant/mc-server (master)]$ npm install

> mc-discourse-sso@1.0.6 postinstall /vagrant/mc-server
> npm run build


> mc-discourse-sso@1.0.6 build /vagrant/mc-server
> babel src --out-dir dist/

sh: 1: babel: not found

npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "node" "/usr/bin/npm" "run" "build"
npm ERR! node v0.10.42
npm ERR! npm  v3.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mc-discourse-sso@1.0.6 build: `babel src --out-dir dist/`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mc-discourse-sso@1.0.6 build script 'babel src --out-dir dist/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mc-discourse-sso package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir dist/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mc-discourse-sso
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mc-discourse-sso
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/mc-server/npm-debug.log
```

**Comment by jacobwgillespie** [comment]
What's the output of `ls ./node_modules/.bin/`?  babel should be in that directory.

**Comment by snowe2010** [comment]
```
[vagrant@precise32:/vagrant/mc-server (master)]$ ls ./node_modules/.bin/
[vagrant@precise32:/vagrant/mc-server (master)]$ ls ./node_modules/.bin/ -al
total 4
drwxrwxrwx 1 vagrant vagrant    0 Feb 23 22:47 .
drwxrwxrwx 1 vagrant vagrant 4096 Feb 24 12:39 ..
[vagrant@precise32:/vagrant/mc-server (master)]$
```

**Comment by jacobwgillespie** [comment]
Interesting - that should have files inside it.  Can you remove line 14 (https://github.com/the-obsidian/mc-discourse-sso/blob/master/package.json#L14) and the comma before it on line 13 from package.json and try running npm install again?  Then after that, post back the contents of the `ls` again.

**Comment by snowe2010** [comment]
```
[vagrant@precise32:/vagrant/mc-server (master)]$ npm install

> mc-discourse-sso@1.0.6 prepublish /vagrant/mc-server
> . ./resources/prepublish.sh

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
[vagrant@precise32:/vagrant/mc-server (master)]$ ls ./node_modules/.bin/ -al
total 4
drwxrwxrwx 1 vagrant vagrant    0 Feb 23 22:47 .
drwxrwxrwx 1 vagrant vagrant 4096 Feb 24 21:07 ..
[vagrant@precise32:/vagrant/mc-server (master)]$
```

**Comment by snowe2010** [comment]
any clue?

**Comment by jacobwgillespie** [comment]
What version of node and npm are you using?  This is me:

```
$ node --version
v5.2.0
$ npm --version
3.3.12
```

**Comment by snowe2010** [comment]
```
[vagrant@precise32:/vagrant (master)]$ node --version
v0.10.42
[vagrant@precise32:/vagrant (master)]$ npm --version
3.7.3
[vagrant@precise32:/vagrant (master)]$

```

**Comment by jacobwgillespie** [comment]
That might do it - Node released a new version after 0.10 called 0.12 then integrated a lot of improvements and released 4.0 - I think the latest version is like 5.7 or something.

**Comment by snowe2010** [comment]
Do I need to install the server globally? `npm install` is now resulting in babel in the node_modules directory, but `npm run build` cannot find babel still. 

edit: oh whoops, well it's still not installing babel to the `node_modules/.bin` directory...

```
[vagrant@precise32:/vagrant/mc-server (master)]$ npm install

> mc-discourse-sso@1.0.6 prepublish /vagrant/mc-server
> . ./resources/prepublish.sh

npm WARN optional Skipping failed optional dependency /babel-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
[vagrant@precise32:/vagrant/mc-server (master)]$ npm run build

> mc-discourse-sso@1.0.6 build /vagrant/mc-server
> babel src --out-dir dist/

sh: 1: babel: not found

npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mc-discourse-sso@1.0.6 build: `babel src --out-dir dist/`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mc-discourse-sso@1.0.6 build script 'babel src --out-dir dist/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mc-discourse-sso package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel src --out-dir dist/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mc-discourse-sso
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mc-discourse-sso
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/mc-server/npm-debug.log
[vagrant@precise32:/vagrant/mc-server (master)]$ ls node_modules/
babel         babel-preset-es2015   body-parser    ect                   express               request
babel-cli     babel-preset-stage-0  cookie-parser  eslint                express-session
babel-eslint  babel-runtime         discourse-sso  eslint-config-airbnb  node-sass-middleware
[vagrant@precise32:/vagrant/mc-server (master)]$

```

**Comment by snowe2010** [comment]
ah I finally got it working. Deleted old `node_modules` folder, reran `npm install` didn't work. Then I moved my mc-discourse-sso folder out of the `/vagrant` folder into `~` and deleted the `node_modules` folder again and then reran `npm install` and everything worked! Thanks for all the help!

**Comment by jacobwgillespie** [comment]
Cool, glad it's working now!
